# Since configuration is shared in umbrella projects, this file
# should only configure the :kandires application itself
# and only for organization purposes. All other config goes to
# the umbrella root.
use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :kandires, KandiresWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false

# watchers: [
#   node: [
#     "node_modules/webpack/bin/webpack.js",
#     "--mode",
#     "development",
#     "--watch-stdin",
#     cd: Path.expand("../assets", __DIR__)
#   ]
# ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :kandires, KandiresWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/kandires_web/live/.*(leex)$},
      ~r{lib/kandires_web/steps/.*(leex|ex)$},
      ~r{lib/kandires_web/views/.*(ex)$},
      ~r{lib/kandires_web/templates/.*(eex)$}
    ]
  ]

config :kandires,
  uploads_directory: "/www/kandires/temp",
  prod_imgs_directory: "/www/kandires/imgs",
  pdftotext_cmd: "/usr/local/bin/pdftotext"

config :exsync, addition_dirs: ["/www/kandis/lib"]

config :kandires, :config,
  local_url: "https://57531e39.ngrok.io",
  # local_url: "https://www.kandires.com.test",
  invoice_url: "/ex/pdfs",
  shop_bcc_recipients: ["werkzeugh@gmail.com"]

config :kandis,
  local_url: "https://57531e39.ngrok.io"

import_config "dev.secret.exs"
